controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    env:
      devoOperatorDvlsAppid: ""
      devoOperatorDvlsBaseuri: ""
      devoOperatorRequeueDuration: 60s
    image:
      repository: devolutions/dvls-kubernetes-operator
      tag: ""
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  replicas: 1
ctrlMgrMetricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
instanceSecret:
  secret: ""
kubernetesClusterDomain: cluster.local
