{{- if .Values.instanceSecret.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-ca-cert
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dvls-kubernetes-operator
    app.kubernetes.io/part-of: dvls-kubernetes-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
stringData:
  ca.crt: {{ .Values.instanceSecret.caCert | quote }}
{{- end }}
