apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-ctrl-mgr-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: dvls-kubernetes-operator
    app.kubernetes.io/part-of: dvls-kubernetes-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ctrlMgrMetricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.ctrlMgrMetricsService.ports | toYaml | nindent 2 }}
