apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-instance-secret
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dvls-kubernetes-operator
    app.kubernetes.io/part-of: dvls-kubernetes-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
stringData:
  secret: {{ required "instanceSecret.secret is required" .Values.instanceSecret.secret
    | quote }}
