# permissions for end users to view dvlssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dvlssecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devolutions-kubernetes-operator
    app.kubernetes.io/part-of: devolutions-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: dvlssecret-viewer-role
rules:
- apiGroups:
  - dvls.devolutions.com
  resources:
  - dvlssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dvls.devolutions.com
  resources:
  - dvlssecrets/status
  verbs:
  - get
