name: release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Check out Devolutions/actions
        uses: actions/checkout@v4
        with:
          repository: Devolutions/actions
          ref: v1
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows

      - name: Set version
        id: get-version
        run: echo "version=$(grep -E '^VERSION[[:space:]]*\?=' Makefile | awk -F'= ' '{print $2}' | tr -d ' ')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ./.github/workflows/create-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get-version.outputs.version }}

  build-image:
    runs-on: ubuntu-latest
    needs: create-release
    environment: container-build

    steps:
      - name: Check out devolutions/dvls-kubernetes-operator
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: devolutionsbot
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            devolutions/dvls-kubernetes-operator:latest
            devolutions/dvls-kubernetes-operator:${{ needs.create-release.outputs.version }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: devolutions/dvls-kubernetes-operator:latest
          ignore-base: true
          only-severities: critical,high
          summary: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: [create-release, build-image]
    environment: helm-publish

    steps:
      - name: Check out dvls-kubernetes-operator
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package chart
        run: helm package chart/

      - name: Check out helm-charts repository
        uses: actions/checkout@v4
        with:
          repository: Devolutions/helm-charts
          token: ${{ secrets.DEVOLUTIONSBOT_WRITE_TOKEN }}
          path: helm-charts

      - name: Copy chart package
        run: cp dvls-kubernetes-operator-*.tgz helm-charts/

      - name: Update index
        working-directory: helm-charts
        run: helm repo index . --url https://devolutions.github.io/helm-charts --merge index.yaml

      - name: Commit and push
        working-directory: helm-charts
        run: |
          git config user.name "devolutionsbot"
          git config user.email "bot@devolutions.net"
          git add dvls-kubernetes-operator/dvls-kubernetes-operator-*.tgz index.yaml
          git commit -m "feat(dvls-kubernetes-operator): add version ${{ needs.create-release.outputs.version }}"
          git push
